# Generated by Django 3.1.2 on 2022-01-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_portal_posts_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64)),
            ],
        ),
    ]
