# Generated by Django 3.1.2 on 2022-02-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_portal_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='user_id_subsriber',
            new_name='user_id_subscriber',
        ),
        migrations.AlterField(
            model_name='posts',
            name='creationtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_info',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='type_posts',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
