# Generated by Django 3.1.2 on 2022-02-10 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20220210_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='subsribe_ornot',
            new_name='subscriber_ornot',
        ),
    ]
