# Generated by Django 3.1.2 on 2022-04-02 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20220210_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='freeze_account',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='influencer_ornot',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='user_id_subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
