# Generated by Django 3.1.2 on 2022-04-06 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeintro', models.CharField(max_length=256, null=True)),
                ('tointro', models.CharField(max_length=256, null=True)),
                ('fromintro', models.CharField(max_length=256, null=True)),
                ('typeoccasion', models.CharField(max_length=256, null=True)),
                ('firstinputoccasion', models.CharField(max_length=256, null=True)),
                ('secondinputoccasion', models.CharField(max_length=256, null=True)),
                ('thirdinputoccasion', models.CharField(max_length=256, null=True)),
                ('fourthinputoccasion', models.CharField(max_length=256, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('user_id_influencerreserve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencerreserve', to=settings.AUTH_USER_MODEL)),
                ('user_id_reserver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
