# Generated by Django 3.1.2 on 2022-04-07 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postandmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_info', models.CharField(max_length=256, null=True)),
                ('creationtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('reservation_ofpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservationofpost', to='network.reservation')),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='portal_id_posts',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='portal_id_subscribing',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='user_id_subscriber',
        ),
        migrations.DeleteModel(
            name='Portal',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
