# Generated by Django 3.1.2 on 2022-04-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20220407_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='influencer_ornot',
            field=models.BooleanField(default=False),
        ),
    ]
