# Generated by Django 3.1.2 on 2022-04-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20220407_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='creationtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
