# Generated by Django 3.1.2 on 2022-04-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_reservation_creationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reviewcompleted',
            field=models.BooleanField(default=False),
        ),
    ]
