# Generated by Django 3.1.2 on 2022-04-09 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_reservation_reviewcompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reservation_foreign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_foreign', to='network.reservation'),
        ),
    ]
