# Generated by Django 3.1.2 on 2022-04-09 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_reviews_reservation_foreign'),
    ]

    operations = [
        migrations.AddField(
            model_name='postandmessage',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posterid', to=settings.AUTH_USER_MODEL),
        ),
    ]
