# Generated by Django 3.1.2 on 2022-04-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photos',
        ),
        migrations.AddField(
            model_name='postandmessage',
            name='video',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
