# Generated by Django 3.1.2 on 2022-04-16 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20220415_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_description', models.CharField(max_length=256, null=True)),
                ('profile_video', models.CharField(max_length=256, null=True)),
                ('profile_fullname', models.CharField(max_length=256, null=True)),
                ('profile_picture', models.CharField(max_length=256, null=True)),
                ('first_url', models.URLField(max_length=256, null=True)),
                ('second_url', models.URLField(max_length=256, null=True)),
                ('third_url', models.URLField(max_length=256, null=True)),
                ('influencer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencer_userinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
