# Generated by Django 3.1.2 on 2022-04-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postandmessage',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
