# Generated by Django 3.1.2 on 2022-04-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_auto_20220418_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteddara',
            name='daradone',
            field=models.BooleanField(default=False),
        ),
    ]
