# Generated by Django 3.1.2 on 2022-04-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_requesteddara_daradone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_stars',
            field=models.IntegerField(null=True),
        ),
    ]
