# Generated by Django 4.0.4 on 2022-04-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_reviews_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
