# Generated by Django 4.0.4 on 2022-04-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0029_reservation_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='duedate',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
