# Generated by Django 4.0.4 on 2022-05-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0031_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
