# Generated by Django 4.0.4 on 2022-05-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0032_reservation_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='realduedate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
