# Generated by Django 4.0.4 on 2022-05-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0034_reservation_completiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='completiondate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='realduedate',
            field=models.DateTimeField(null=True),
        ),
    ]
