# Generated by Django 4.0.4 on 2022-05-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0035_alter_reservation_completiondate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maillistlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
