# Generated by Django 4.0.4 on 2022-05-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0037_reporttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttable',
            name='influencer',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='reporttable',
            name='requester',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
