# Generated by Django 4.0.4 on 2022-05-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0038_alter_reporttable_influencer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
