# Generated by Django 4.0.4 on 2022-05-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0039_reservation_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='omiserecipent',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
