# Generated by Django 3.2.13 on 2022-05-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0043_reservationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='chargestatus',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ReservationStatus',
        ),
    ]
