# Generated by Django 3.2.13 on 2022-05-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0045_user_accountstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountstatus',
            field=models.CharField(default='1', max_length=256),
        ),
    ]
