# Generated by Django 3.2.13 on 2022-05-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0046_alter_user_accountstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountstatus',
            field=models.IntegerField(default=1),
        ),
    ]
