# Generated by Django 4.0.6 on 2022-07-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0049_passwordadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='orderid',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
