# Generated by Django 3.2.13 on 2022-06-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0050_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
