# Generated by Django 3.2.13 on 2022-06-29 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0051_userinfo_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='order_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='Reservationlive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.CharField(max_length=256, null=True)),
                ('time2', models.CharField(max_length=256, null=True)),
                ('time3', models.CharField(max_length=256, null=True)),
                ('liveroomid', models.CharField(max_length=256, null=True)),
                ('timeuse', models.CharField(max_length=256, null=True)),
                ('liveinfo', models.CharField(max_length=256, null=True)),
                ('order_id', models.CharField(max_length=256, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('creationtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('completiondate', models.DateTimeField(null=True)),
                ('omisecharge', models.CharField(max_length=256, null=True)),
                ('chargestatus', models.BooleanField(default=False)),
                ('user_id_influencerreserve_live', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencerreservelive', to=settings.AUTH_USER_MODEL)),
                ('user_id_reserver_live', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserverlive', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
