# Generated by Django 3.2.13 on 2022-07-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0053_auto_20220701_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='livevdotime',
            field=models.BooleanField(default=True),
        ),
    ]
