# Generated by Django 3.2.13 on 2022-07-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0054_userinfo_livevdotime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='livevdotime',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
