# Generated by Django 3.2.13 on 2022-07-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0056_alter_userinfo_livevdotime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationlive',
            name='status',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
