# Generated by Django 3.2.13 on 2022-07-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0057_reservationlive_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationlive',
            name='status',
            field=models.CharField(default='ok', max_length=256, null=True),
        ),
    ]
